name = "obsidian-gateway"
main = "worker.js"
compatibility_date = "2024-01-01"

# Routes configuration for custom domain
routes = [
  { pattern = "obsidian.notebooksyncer.com/*", custom_domain = true }
]

# Environment variables (optional)
[env.production]
name = "obsidian-gateway"

[env.development]
name = "obsidian-gateway-dev"